# cogs/pokemons.py
"""
Source of truth for auctionable Pokémon.

Exports:
- POKEMONS_BY_GEN: Dict[int, List[str]]
- ALL_POKEMONS: List[str]
- POKEMONS: alias to ALL_POKEMONS (backward-compat)
- NAME_TO_CANON: Dict[str, str]  (lowercase -> canonical)
- Functions:
    canon(name) -> Optional[str]
    in_whitelist(name) -> bool
    by_gen(gen: int) -> list[str]
    by_gens(gens: list[int]) -> list[str]
    parse_gens(text: str) -> list[int]      # e.g. "1,3-5" -> [1,3,4,5]
    validate_names(names: list[str]) -> tuple[list[str], list[str]]  # (valid_canon, invalid_raw)
    expand_copies(name: str, count: int) -> list[str]                # e.g. ("Incineroar", 3) -> ["Incineroar","Incineroar","Incineroar"]
    list_names() -> list[str]
    get_named_list(name: str) -> list[str]
"""

from __future__ import annotations
from typing import Dict, List, Tuple, Optional

# ---------------- Data, organized by generation ---------------- #

POKEMONS_BY_GEN: Dict[int, List[str]] = {
    1: [
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Bellossom",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Drowzee",
        "Hypno",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Hitmonlee",
        "Hitmonchan",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Scyther",
        "Electabuzz",
        "Magmar",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Espeon",
        "Umbreon",
        "Porygon",
        "Snorlax",
        "Dratini",
        "Dragonair",
        "Dragonite",
    ],
    2: [
        "Chikorita",
        "Bayleef",
        "Meganium",
        "Cyndaquil",
        "Quilava",
        "Typhlosion",
        "Totodile",
        "Croconaw",
        "Feraligatr",
        "Sentret",
        "Furret",
        "Hoothoot",
        "Noctowl",
        "Spinarak",
        "Ariados",
        "Chinchou",
        "Lanturn",
        "Mareep",
        "Flaaffy",
        "Ampharos",
        "Marill",
        "Azumarill",
        "Hoppip",
        "Skiploom",
        "Jumpluff",
        "Aipom",
        "Sunkern",
        "Sunflora",
        "Yanma",
        "Wooper",
        "Quagsire",
        "Murkrow",
        "Misdreavus",
        "Girafarig",
        "Pineco",
        "Forretress",
        "Dunsparce",
        "Gligar",
        "Snubbull",
        "Granbull",
        "Qwilfish",
        "Heracross",
        "Sneasel",
        "Teddiursa",
        "Ursaring",
        "Slugma",
        "Magcargo",
        "Swinub",
        "Piloswine",
        "Delibird",
        "Skarmory",
        "Houndour",
        "Houndoom",
        "Phanpy",
        "Donphan",
        "Stantler",
        "Smeargle",
        "Tyrogue",
        "Hitmontop",
        "Larvitar",
        "Pupitar",
        "Tyranitar",
    ],
    3: [
        "Treecko",
        "Grovyle",
        "Sceptile",
        "Torchic",
        "Combusken",
        "Blaziken",
        "Mudkip",
        "Marshtomp",
        "Swampert",
        "Poochyena",
        "Mightyena",
        "Lotad",
        "Lombre",
        "Ludicolo",
        "Seedot",
        "Nuzleaf",
        "Shiftry",
        "Wingull",
        "Pelipper",
        "Ralts",
        "Kirlia",
        "Gardevoir",
        "Gallade",
        "Surskit",
        "Masquerain",
        "Shroomish",
        "Breloom",
        "Slakoth",
        "Vigoroth",
        "Slaking",
        "Makuhita",
        "Hariyama",
        "Nosepass",
        "Sableye",
        "Meditite",
        "Medicham",
        "Plusle",
        "Minun",
        "Volbeat",
        "Illumise",
        "Gulpin",
        "Swalot",
        "Numel",
        "Camerupt",
        "Torkoal",
        "Spoink",
        "Grumpig",
        "Trapinch",
        "Vibrava",
        "Flygon",
        "Cacnea",
        "Cacturne",
        "Swablu",
        "Altaria",
        "Zangoose",
        "Seviper",
        "Barboach",
        "Whiscash",
        "Corphish",
        "Crawdaunt",
        "Feebas",
        "Milotic",
        "Shuppet",
        "Banette",
        "Duskull",
        "Dusclops",
        "Tropius",
        "Chimecho",
        "Snorunt",
        "Glalie",
        "Froslass",
        "Bagon",
        "Shelgon",
        "Salamence",
        "Beldum",
        "Metang",
        "Metagross",
    ],
    4: [
        "Turtwig",
        "Grotle",
        "Torterra",
        "Chimchar",
        "Monferno",
        "Infernape",
        "Piplup",
        "Prinplup",
        "Empoleon",
        "Starly",
        "Staravia",
        "Staraptor",
        "Kricketot",
        "Kricketune",
        "Shinx",
        "Luxio",
        "Luxray",
        "Cranidos",
        "Rampardos",
        "Shieldon",
        "Bastiodon",
        "Combee",
        "Vespiquen",
        "Pachirisu",
        "Buizel",
        "Floatzel",
        "Shellos",
        "Gastrodon",
        "Drifloon",
        "Drifblim",
        "Stunky",
        "Skuntank",
        "Bronzor",
        "Bronzong",
        "Gible",
        "Gabite",
        "Garchomp",
        "Riolu",
        "Lucario",
        "Hippopotas",
        "Hippowdon",
        "Croagunk",
        "Toxicroak",
        "Finneon",
        "Lumineon",
        "Snover",
        "Abomasnow",
        "Rotom",
    ],
    5: [
        "Snivy",
        "Servine",
        "Serperior",
        "Tepig",
        "Pignite",
        "Emboar",
        "Oshawott",
        "Dewott",
        "Samurott",
        "Drilbur",
        "Excadrill",
        "Timburr",
        "Gurdurr",
        "Conkeldurr",
        "Sewaddle",
        "Swadloon",
        "Leavanny",
        "Cottonee",
        "Whimsicott",
        "Petilil",
        "Lilligant",
        "Basculin",
        "Sandile",
        "Krokorok",
        "Krookodile",
        "Scraggy",
        "Scrafty",
        "Zorua",
        "Zoroark",
        "Minccino",
        "Cinccino",
        "Gothita",
        "Gothorita",
        "Gothitelle",
        "Solosis",
        "Duosion",
        "Reuniclus",
        "Ducklett",
        "Swanna",
        "Deerling",
        "Sawsbuck",
        "Foongus",
        "Amoonguss",
        "Joltik",
        "Galvantula",
        "Eelektrik",
        "Eelektross",
        "Litwick",
        "Lampent",
        "Chandelure",
        "Axew",
        "Fraxure",
        "Haxorus",
        "Cubchoo",
        "Beartic",
        "Cryogonal",
        "Mienfoo",
        "Mienshao",
        "Golett",
        "Golurk",
        "Pawniard",
        "Bisharp",
        "Rufflet",
        "Braviary",
        "Vullaby",
        "Mandibuzz",
        "Deino",
        "Zweilous",
        "Hydreigon",
        "Larvesta",
        "Volcarona",
    ],
    6: [
        "Chespin",
        "Quilladin",
        "Chesnaught",
        "Fennekin",
        "Braixen",
        "Delphox",
        "Froakie",
        "Frogadier",
        "Greninja",
        "Fletchling",
        "Fletchinder",
        "Talonflame",
        "Scatterbug",
        "Spewpa",
        "Vivillon",
        "Litleo",
        "Pyroar",
        "Flabébé",
        "Floette",
        "Florges",
        "Skiddo",
        "Gogoat",
        "Espurr",
        "Meowstic",
        "Inkay",
        "Malamar",
        "Skrelp",
        "Dragalge",
        "Clauncher",
        "Clawitzer",
        "Hawlucha",
        "Dedenne",
        "Carbink",
        "Goomy",
        "Sliggoo",
        "Goodra",
        "Klefki",
        "Phantump",
        "Trevenant",
        "Bergmite",
        "Avalugg",
        "Noibat",
        "Noivern",
    ],
    7: [
        "Rowlet",
        "Dartrix",
        "Decidueye",
        "Litten",
        "Torracat",
        "Incineroar",
        "Popplio",
        "Brionne",
        "Primarina",
        "Pikipek",
        "Trumbeak",
        "Toucannon",
        "Yungoos",
        "Gumshoos",
        "Grubbin",
        "Charjabug",
        "Vikavolt",
        "Crabrawler",
        "Crabominable",
        "Oricorio",
        "Rockruff",
        "Lycanroc",
        "Mareanie",
        "Toxapex",
        "Mudbray",
        "Mudsdale",
        "Dewpider",
        "Araquanid",
        "Fomantis",
        "Lurantis",
        "Salandit",
        "Salazzle",
        "Bounsweet",
        "Steenee",
        "Tsareena",
        "Comfey",
        "Oranguru",
        "Sandygast",
        "Palossand",
        "Minior",
        "Komala",
        "Mimikyu",
        "Bruxish",
        "Jangmo-o",
        "Hakamo-o",
        "Kommo-o",
    ],
    8: [
        "Grookey",
        "Thwackey",
        "Rillaboom",
        "Scorbunny",
        "Raboot",
        "Cinderace",
        "Sobble",
        "Drizzile",
        "Inteleon",
        "Skwovet",
        "Greedent",
        "Rookidee",
        "Corvisquire",
        "Corviknight",
        "Chewtle",
        "Drednaw",
        "Rolycoly",
        "Carkol",
        "Coalossal",
        "Applin",
        "Flapple",
        "Appletun",
        "Silicobra",
        "Sandaconda",
        "Cramorant",
        "Arrokuda",
        "Barraskewda",
        "Toxel",
        "Toxtricity",
        "Sinistea",
        "Polteageist",
        "Hatenna",
        "Hattrem",
        "Hatterene",
        "Impidimp",
        "Morgrem",
        "Grimmsnarl",
        "Milcery",
        "Alcremie",
        "Falinks",
        "Pincurchin",
        "Snom",
        "Frosmoth",
        "Stonjourner",
        "Eiscue",
        "Indeedee",
        "Morpeko",
        "Copperajah",
        "Duraludon",
        "Dragapult",
    ],
    9: [
        "Wyrdeer",  # Hisuian evo, included as provided
        "Sprigatito",
        "Floragato",
        "Meowscarada",
        "Fuecoco",
        "Crocalor",
        "Skeledirge",
        "Quaxly",
        "Quaxwell",
        "Quaquaval",
        "Lechonk",
        "Oinkologne",
        "Spidops",
        "Pawmi",
        "Pawmo",
        "Pawmot",
        "Tandemaus",
        "Maushold",
        "Fidough",
        "Dachsbun",
        "Smoliv",
        "Dolliv",
        "Arboliva",
        "Squawkabilly",
        "Nacli",
        "Naclstack",
        "Garganacl",
        "Charcadet",
        "Armarouge",
        "Ceruledge",
        "Bellibolt",
        "Wattrel",
        "Kilowattrel",
        "Maschiff",
        "Mabosstiff",
        "Shroodle",
        "Grafaiai",
        "Bramblin",
        "Brambleghast",
        "Toedscool",
        "Toedscruel",
        "Klawf",
        "Capsakid",
        "Scovillain",
        "Rellor",
        "Rabsca",
        "Flittle",
        "Espathra",
        "Tinkatink",
        "Tinkatuff",
        "Tinkaton",
        "Wiglett",
        "Wugtrio",
        "Bombirdier",
        "Finizen",
        "Palafin",
        "Varoom",
        "Revavroom",
        "Cyclizar",
        "Orthworm",
        "Gimmighoul",
        "Gholdengo",
        "Greavard",
        "Houndstone",
        "Flamigo",
        "Cetoddle",
        "Cetitan",
        "Veluza",
        "Dondozo",
        "Tatsugiri",
        "Frigibax",
        "Arctibax",
        "Baxcalibur",
        "Poltchageist",
        "Sinistcha",
    ],
}

# --- Curated meta usage list (~top 50) ---
META_USAGE_TOP50: List[str] = [
    "Gholdengo",
    "Dragonite",
    "Archaludon",
    "Incineroar",
    "Rillaboom",
    "Ursaluna-Bloodmoon",
    "Annihilape",
    "Sneasler",
    "Pelipper",
    "Whimsicott",
    "Amoonguss",
    "Volcarona",
    "Ursaluna",
    "Dondozo",
    "Indeedee",
    "Kingambit",
    "Maushold",
    "Tatsugiri",
    "Garchomp",
    "Sinistcha",
    "Ninetales-Alola",
    "Basculegion",
    "Primarina",
    "Electabuzz",
    "Talonflame",
    "Torkoal",
    "Tauros-Paldea-Blaze",
    "Porygon2",
    "Indeedee-F",
    "Tyranitar",
    "Grimmsnarl",
    "Typhlosion-Hisui",
    "Farigiraf",
    "Dragapult",
    "Murkrow",
    "Politoed",
    "Gothitelle",
    "Kingdra",
    "Corviknight",
    "Baxcalibur",
    "Magmar",
    "Gallade",
    "Kilowattrel",
    "Armarouge",
    "Weezing-Galar",
    "Hatterene",
    "Smeargle",
    "Kommo-o",
    "Excadrill",
    "Lilligant-Hisui",
]

# Registry of named lists
NAMED_LISTS: Dict[str, List[str]] = {
    "meta": META_USAGE_TOP50,
}

# ---------------- Flattened & Canonical ---------------- #

ALL_POKEMONS: List[str] = [
    p for gen in sorted(POKEMONS_BY_GEN) for p in POKEMONS_BY_GEN[gen]
]
POKEMONS: List[str] = ALL_POKEMONS
NAME_TO_CANON: Dict[str, str] = {p.lower(): p for p in ALL_POKEMONS}

# ---------------- Helper functions ---------------- #


def canon(name: str) -> Optional[str]:
    if not name:
        return None
    return NAME_TO_CANON.get(name.strip().lower())


def in_whitelist(name: str) -> bool:
    return canon(name) is not None


def by_gen(gen: int) -> List[str]:
    return list(POKEMONS_BY_GEN.get(int(gen), []))


def by_gens(gens: List[int]) -> List[str]:
    seen = set()
    out: List[str] = []
    for g in sorted({int(x) for x in gens}):
        for p in POKEMONS_BY_GEN.get(g, []):
            if p not in seen:
                seen.add(p)
                out.append(p)
    return out


def parse_gens(text: str) -> List[int]:
    if not text:
        return []
    text = text.replace(" ", "")
    gens: List[int] = []
    for part in text.split(","):
        if "-" in part:
            a, b = part.split("-", 1)
            try:
                start, end = int(a), int(b)
                if start <= end:
                    gens.extend(range(start, end + 1))
                else:
                    gens.extend(range(end, start + 1))
            except ValueError:
                continue
        else:
            try:
                gens.append(int(part))
            except ValueError:
                continue
    return [g for g in sorted(set(gens)) if g in POKEMONS_BY_GEN]


def validate_names(names: List[str]) -> Tuple[List[str], List[str]]:
    valid: List[str] = []
    invalid: List[str] = []
    for n in names:
        c = canon(n)
        if c:
            valid.append(c)
        else:
            invalid.append(n)
    return valid, invalid


def expand_copies(name: str, count: int) -> List[str]:
    c = canon(name)
    if not c or count <= 0:
        return []
    return [c] * int(count)


def list_names() -> List[str]:
    return sorted(NAMED_LISTS.keys())


def get_named_list(name: str) -> List[str]:
    key = name.strip().lower()
    raw = NAMED_LISTS.get(key, [])
    out: List[str] = []
    for n in raw:
        c = canon(n)
        if c:
            out.append(c)
    seen: set[str] = set()
    uniq: List[str] = []
    for n in out:
        if n not in seen:
            seen.add(n)
            uniq.append(n)
    return uniq


__all__ = [
    "POKEMONS_BY_GEN",
    "ALL_POKEMONS",
    "POKEMONS",
    "NAME_TO_CANON",
    "canon",
    "in_whitelist",
    "by_gen",
    "by_gens",
    "parse_gens",
    "validate_names",
    "expand_copies",
    "META_USAGE_TOP50",
    "NAMED_LISTS",
    "list_names",
    "get_named_list",
]
